### ISSUE TITLE
Token logger

### ISSUE THREAD

**Issue by Tropixi** [MapleHackersoff/AlphaSpammer#1]
This is a token logger for those of you who don't know I got token logged.
https://github.com/Sheepy132/Alpha-Spammer

**Comment by MapleHackersoff** [comment]
it isn`t token logger lol, u have proofs?

**Comment by Tropixi** [comment]
Yep run with vt

**Comment by MapleHackersoff** [comment]
and?

**Comment by Tropixi** [comment]
It's a virus sir

**Comment by MapleHackersoff** [comment]
proofs ;-;
its alphaspammr original ver lol

**Comment by Tropixi** [comment]
This is a token logger buddy

**Comment by Tropixi** [comment]
Their's literaly 30 alpha spammers all over github

**Comment by MapleHackersoff** [comment]
okay, but its original Alpha Spammer. n~ i downloaded it 4m Sheppy`s github
